android.useAndroidX=true
android.enableJetifier=true
kotlin.code.style=official
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

SUPABASE_URL=https://qfotxfxzgcnbmtznlhfc.supabase.co
SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFmb3R4Znh6Z2NuYm10em5saGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODY4NzAzMzksImV4cCI6MjEwMjQ0NjMzOX0.Gz6uMvUyHNjycELIEaggOAo-SrseaM1-2Yp_CTRa8MU
API_BASE_URL=https://byemidias.vercel.app
